In [62]:
import warnings
warnings.filterwarnings("ignore")

In [7]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\vaibhav rathod\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: openpyxl in c:\users\vaibhav rathod\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vaibhav rathod\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vaibhav rathod\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vaibhav rathod\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vaibhav rathod\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: et-xmlfile in c:\users\vaibhav rathod\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\vaibhav rathod\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [9]:
import os

file_path = r'C:\Users\Vaibhav Rathod\Desktop\Nilay\Assignments\Assiggment questions\Recommendation System\anime.xlsx'

if os.path.exists(file_path):
    print("File exists!")
else:
    print("File not found!")

File not found!

In [14]:
print(file_path)

C:\Users\Vaibhav Rathod\Desktop\Nilay\Assignments\Assiggment questions\Recommendation System\anime.xlsx

In [15]:
import os

if os.path.exists(file_path):
    print("File exists")
else:
    print("File does not exist")

File does not exist

In [16]:
import os

absolute_path = os.path.abspath(file_path)
print("Absolute file path:", absolute_path)

Absolute file path: C:\Users\Vaibhav Rathod\Desktop\Nilay\Assignments\Assiggment questions\Recommendation System\anime.xlsx

In [17]:
file_path = 'C:\\Users\\Vaibhav Rathod\\Desktop\\Nilay\\Assignments\\Assiggment questions\\Recommendation System\\anime.xlsx'

In [19]:
file_path = 'anime.xlsx'

In [20]:
import os

if os.path.exists(file_path):
    print("File exists")
else:
    print("File does not exist")

File does not exist

In [21]:
import pandas as pd
print("Pandas version:", pd.__version__)

Pandas version: 2.2.3

In [22]:
import openpyxl
print("openpyxl version:", openpyxl.__version__)

openpyxl version: 3.1.5

In [23]:
file_path = r"C:\Users\Vaibhav Rathod\Desktop\Nilay\Assignments\Assiggment questions\Recommendation System\anime.xlsx"
print(file_path)

C:\Users\Vaibhav Rathod\Desktop\Nilay\Assignments\Assiggment questions\Recommendation System\anime.xlsx

In [24]:
import os

file_path = r"C:\Users\Vaibhav Rathod\Desktop\Nilay\Assignments\Assiggment questions\Recommendation System\anime.xlsx"

if os.path.exists(file_path):
    print("File exists and is accessible.")
else:
    print("File does not exist or cannot be accessed.")

File does not exist or cannot be accessed.

In [29]:
import pandas as pd

df = pd.read_csv('C:\\Users\\Vaibhav Rathod\\Desktop\\Nilay\\Assignments\\Assiggment questions\\Recommendation System\\anime.csv')

In [26]:
import os
print(os.getcwd())

C:\Users\Vaibhav Rathod\Desktop\Nilay\Assignments\Assiggment questions\Recommendation System

In [31]:
import os
file_path = os.path.join('C:\\', 'Users', 'Vaibhav Rathod', 'Desktop', 'Nilay', 'Assignments', 'Assiggment questions', 'Recommendation System', 'anime.csv')
df = pd.read_csv(file_path)

In [84]:
df= pd.read_csv("anime.csv")
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [85]:
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [86]:
df.sample(5)

,anime_id,name,genre,type,episodes,rating,members
8570,20093,Furiten-kun,"Comedy, Seinen, Slice of Life",Movie,1,6.56,67
10104,32559,Ryuuzou to Shichinin no Kobun-tachi x Frogman,Comedy,ONA,5,4.29,41
5944,3808,Futari Daka,"Cars, Shounen, Sports",TV,36,6.30,234
9314,33123,Koto Nakare Hero Gingerman,Comedy,TV,12,3.80,39
738,2582,Soukou Kihei Votoms,"Action, Drama, Mecha, Military, Sci-Fi, Space",TV,52,7.87,9008

In [87]:
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

Rows: 12294, Columns: 7

In [88]:
print("Columns:", df.columns.tolist())

Columns: ['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members']

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [90]:
df.describe()

           anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [91]:
df.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [92]:
print(df.columns)

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [93]:
if 'genres' in df.columns:
    df['genres'] = df['genres'].fillna('')
    genres_split = df['genres'].str.get_dummies(sep=',')
else:
    print("The 'genres' column is missing.")

The 'genres' column is missing.

In [94]:
df.columns = df.columns.str.strip()  # Remove leading/trailing spaces from column names

In [95]:
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [96]:
# One-hot encode 'Type'
type_encoded = pd.get_dummies(df['type'], prefix='type')

# Multi-hot encode 'Genres' (assuming genres are comma-separated)
df['genre'] = df['genre'].fillna('')  # Replace NaN with empty string
genres_split = df['genre'].str.get_dummies(sep=',')

In [97]:
print(df.columns)

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [98]:
df.columns = df.columns.str.strip()  # Remove leading/trailing spaces from column names

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12294 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [105]:
df["episodes"] = df["episodes"].astype("float")

ValueError: could not convert string to float: 'Unknown'

In [99]:
if 'rating' in df.columns:
    df[['rating', 'episodes']] = scaler.fit_transform(df[['rating', 'episodes']])
else:
    print("'rating' column is missing.")

ValueError: could not convert string to float: 'Unknown'

In [79]:
df['popularity'] = df.get('popularity', pd.Series([0] * len(df)))  # Use 0 or any value as placeholder

In [57]:
print(df[['rating', 'popularity', 'episodes']].info())
print(df[['rating', 'popularity', 'episodes']].describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rating      12064 non-null  float64
 1   popularity  12294 non-null  int64
 2   episodes    12294 non-null  object
dtypes: float64(1), int64(1), object(1)
memory usage: 288.3+ KB
None
             rating  popularity
count  12064.000000     12294.0
mean       6.473902         0.0
std        1.026746         0.0
min        1.670000         0.0
25%        5.880000         0.0
50%        6.570000         0.0
75%        7.180000         0.0
max       10.000000         0.0

In [60]:
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')  # Coerce errors to NaN
df['popularity'] = pd.to_numeric(df['popularity'], errors='coerce')
df['episodes'] = pd.to_numeric(df['episodes'], errors='coerce')

In [63]:
df['rating'].fillna(df['rating'].mean(), inplace=True)
df['popularity'].fillna(df['popularity'].mean(), inplace=True)
df['episodes'].fillna(df['episodes'].mean(), inplace=True)

In [64]:
scaler = MinMaxScaler()
df[['rating', 'popularity', 'episodes']] = scaler.fit_transform(df[['rating', 'popularity', 'episodes']])

In [65]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Example dataframe
df = pd.DataFrame({
    'rating': [8.5, 'Unknown', 7.0],
    'popularity': [500, 'Unknown', 300],
    'episodes': [24, 12, 'Unknown']
})

# Convert non-numeric to NaN
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
df['popularity'] = pd.to_numeric(df['popularity'], errors='coerce')
df['episodes'] = pd.to_numeric(df['episodes'], errors='coerce')

# Fill missing values with mean
df['rating'].fillna(df['rating'].mean(), inplace=True)
df['popularity'].fillna(df['popularity'].mean(), inplace=True)
df['episodes'].fillna(df['episodes'].mean(), inplace=True)

# Normalize the data
scaler = MinMaxScaler()
df[['rating', 'popularity', 'episodes']] = scaler.fit_transform(df[['rating', 'popularity', 'episodes']])

print(df)

   rating  popularity  episodes
0     1.0         1.0       1.0
1     0.5         0.5       0.0
2     0.0         0.0       0.5

In [67]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Normalize numerical features (e.g., 'rating', 'popularity', 'episodes')
scaler = MinMaxScaler()
df[['rating', 'popularity', 'episodes']] = scaler.fit_transform(df[['rating', 'popularity', 'episodes']])

In [68]:
# Combine all features into a single DataFrame
df_preprocessed = pd.concat([df[['rating', 'popularity', 'episodes']], type_encoded, genres_split], axis=1)

In [69]:
# Check for missing values
print(df_preprocessed.isnull().sum().sum())

# Display the preprocessed DataFrame
df_preprocessed.head()

36873

,rating,popularity,episodes,type_Movie,type_Music,type_ONA,type_OVA,type_Special,type_TV,Adventure,...,Shoujo,Shounen,Slice of Life,Space,Sports,Super Power,Supernatural,Thriller,Vampire,Yaoi
0,1.0,1.0,1.0,True,False,False,False,False,False,0,...,0,0,0,0,0,0,0,0,0,0
1,0.5,0.5,0.0,False,False,False,False,False,True,1,...,0,0,0,0,0,0,0,0,0,0
2,0.0,0.0,0.5,False,False,False,False,False,True,0,...,0,0,0,0,0,0,0,0,0,0
3,NaN,NaN,NaN,False,False,False,False,False,True,0,...,0,0,0,0,0,0,0,0,0,0
4,NaN,NaN,NaN,False,False,False,False,False,True,0,...,0,0,0,0,0,0,0,0,0,0

In [70]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler
import numpy as np

def recommend_anime(df, anime_index, n_recommendations=5):
    """
    Recommend anime based on cosine similarity.
    
    Parameters:
    - df: DataFrame containing the anime dataset
    - anime_index: Index of the anime in the DataFrame for which we want recommendations
    - n_recommendations: Number of recommendations to return
    
    Returns:
    - DataFrame containing the top `n_recommendations` most similar anime
    """
    # 1. Data preprocessing
    # Select relevant columns (ratings, episodes, etc.) and one-hot encode categorical columns
    df_clean = df[['rating', 'episodes', 'popularity']]  # Or add any other features
    df_clean['rating'] = pd.to_numeric(df_clean['rating'], errors='coerce')
    df_clean['episodes'] = pd.to_numeric(df_clean['episodes'], errors='coerce')
    df_clean['popularity'] = pd.to_numeric(df_clean['popularity'], errors='coerce')

    # Fill missing values (using mean of the column for simplicity)
    df_clean['rating'].fillna(df_clean['rating'].mean(), inplace=True)
    df_clean['episodes'].fillna(df_clean['episodes'].mean(), inplace=True)
    df_clean['popularity'].fillna(df_clean['popularity'].mean(), inplace=True)

    # Normalize numerical features
    scaler = MinMaxScaler()
    df_clean[['rating', 'popularity', 'episodes']] = scaler.fit_transform(df_clean[['rating', 'popularity', 'episodes']])

    # 2. Compute cosine similarity matrix
    similarity_matrix = cosine_similarity(df_clean)

    # 3. Get the similarities for the given anime_index
    similarity_scores = similarity_matrix[anime_index]

    # 4. Get indices of top `n_recommendations` excluding the anime itself
    similar_indices = similarity_scores.argsort()[-n_recommendations-1:-1][::-1]
    
    # 5. Return the recommendations
    recommended_anime = df.iloc[similar_indices]
    return recommended_anime

# Example usage (Assuming 'df' i the anime DataFrame with at least 'rating', 'episodes', 'popularity')
# recommended_anime = recommend_anime(df, anime_index=0, n_recommendations=5)

In [71]:
recommended_anime = recommend_anime(df, anime_index=0, n_recommendations=5)
print(recommended_anime)

   rating  popularity  episodes
1     0.5         0.5       0.0
2     0.0         0.0       0.5

In [73]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler

def recommend_anime_with_threshold(df, target_index, similarity_threshold=0.5, n_recommendations=10):
    """
    Recommend anime similar to the target anime based on cosine similarity with a threshold filter.
    
    Parameters:
    - df: DataFrame containing the anime dataset
    - target_index: Index of the target anime in the DataFrame
    - similarity_threshold: Minimum similarity score for recommendations (0 to 1)
    - n_recommendations: Maximum number of recommendations to return
    
    Returns:
    - DataFrame with the most similar anime that pass the similarity threshold
    """
    # Check the size of the DataFrame to avoid out of bounds error
    if target_index >= len(df):
        raise IndexError(f"Target index {target_index} is out of bounds for the DataFrame with {len(df)} rows.")
    
    # 1. Data preprocessing
    # Select relevant columns (e.g., rating, episodes, popularity)
    df_clean = df[['rating', 'episodes', 'popularity']]  # Add other features if needed
    df_clean['rating'] = pd.to_numeric(df_clean['rating'], errors='coerce')
    df_clean['episodes'] = pd.to_numeric(df_clean['episodes'], errors='coerce')
    df_clean['popularity'] = pd.to_numeric(df_clean['popularity'], errors='coerce')

    # Fill missing values with the mean of the column
    df_clean['rating'].fillna(df_clean['rating'].mean(), inplace=True)
    df_clean['episodes'].fillna(df_clean['episodes'].mean(), inplace=True)
    df_clean['popularity'].fillna(df_clean['popularity'].mean(), inplace=True)

    # Normalize numerical features
    scaler = MinMaxScaler()
    df_clean[['rating', 'popularity', 'episodes']] = scaler.fit_transform(df_clean[['rating', 'popularity', 'episodes']])

    # 2. Compute cosine similarity matrix
    similarity_matrix = cosine_similarity(df_clean)

    # 3. Get similarity scores for the target anime
    similarity_scores = similarity_matrix[target_index]

    # 4. Filter out anime below the similarity threshold and create a list of recommendations
    similar_anime = [(index, score) for index, score in enumerate(similarity_scores) if score > similarity_threshold and index != target_index]

    # Sort the recommendations by similarity score in descending order
    similar_anime = sorted(similar_anime, key=lambda x: x[1], reverse=True)

    # 5. Limit to `n_recommendations` and return the result
    top_recommendations = similar_anime[:n_recommendations]

    # Get the indices of the recommended anime
    recommended_indices = [index for index, _ in top_recommendations]

    # Return the recommended anime from the DataFrame
    recommended_anime = df.iloc[recommended_indices]
    
    return recommended_anime

# Example usage:
# Assuming `df` is the anime DataFrame with at least 3 rows
# Adjust similarity threshold to experiment with different recommendation sizes
try:
    recommended_anime = recommend_anime_with_threshold(df, target_index=5, similarity_threshold=0.7, n_recommendations=5)
    print(recommended_anime[['name', 'rating', 'episodes']])
except IndexError as e:
    print(e)

Target index 5 is out of bounds for the DataFrame with 3 rows.

In [74]:
print(df.shape)

(3, 3)

In [106]:
print(recommended_anime.columns)

Index(['rating', 'popularity', 'episodes'], dtype='object')

In [109]:
print(df.columns)

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [110]:
df_clean = df[['rating', 'episodes']]  # Use only 'rating' and 'episodes'

In [111]:
print(recommended_anime.columns)

Index(['rating', 'popularity', 'episodes'], dtype='object')

In [113]:
df_clean = df[['rating', 'episodes']]  # Only keep 'rating' and 'episodes'

In [114]:
print(df.columns)

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [116]:
df_clean = df[['rating', 'episodes']].dropna()

In [118]:
# Convert columns to numeric, forcing non-numeric values to NaN
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
df['episodes'] = pd.to_numeric(df['episodes'], errors='coerce')

# Fill NaN values with the mean of each column
df_clean = df[['rating', 'episodes']].fillna(df[['rating', 'episodes']].mean())

In [119]:
def recommend_anime_with_threshold(df, target_index, similarity_threshold=0.7, n_recommendations=5):
    # Ensure the target_index is valid
    if target_index >= len(df) or target_index < 0:
        raise IndexError(f"Target index {target_index} is out of bounds for the DataFrame with {len(df)} rows.")
    
    # 1. Data preprocessing (select relevant columns)
    df_clean = df[['rating', 'episodes']].dropna()  # Remove rows with NaN values
    
    # 2. Normalize numerical features
    df_clean['rating'] = pd.to_numeric(df_clean['rating'], errors='coerce')
    df_clean['episodes'] = pd.to_numeric(df_clean['episodes'], errors='coerce')
    
    scaler = MinMaxScaler()
    df_clean[['rating', 'episodes']] = scaler.fit_transform(df_clean[['rating', 'episodes']])
    
    # 3. Calculate cosine similarity between anime
    similarity_matrix = cosine_similarity(df_clean)
    
    # 4. Get similarity scores for the target anime
    similarity_scores = similarity_matrix[target_index]
    
    # 5. Filter out anime below the similarity threshold
    similar_anime = [(index, score) for index, score in enumerate(similarity_scores) if score > similarity_threshold and index != target_index]
    
    # Sort by similarity score in descending order
    similar_anime = sorted(similar_anime, key=lambda x: x[1], reverse=True)
    
    # 6. Get top recommendations
    recommended_anime = [df.iloc[index] for index, _ in similar_anime[:n_recommendations]]
    
    return pd.DataFrame(recommended_anime)

# Example usage:
recommended_anime = recommend_anime_with_threshold(df, target_index=0, similarity_threshold=0.7, n_recommendations=5)
print(recommended_anime[['name', 'rating', 'episodes']])

                                                 name  rating  episodes
8   Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...    9.10       1.0
11                                     Koe no Katachi    9.05       1.0
15                      Sen to Chihiro no Kamikakushi    8.93       1.0
18                       Ookami Kodomo no Ame to Yuki    8.84       1.0
24                                      Mononoke Hime    8.81       1.0

In [120]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
X = df_clean.drop('rating', axis=1)  # Features
y = df_clean['rating']  # Target variable

# Splitting the data into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shape of the split data
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((9835, 1), (2459, 1), (9835,), (2459,))

In [121]:
from sklearn.metrics import precision_score, recall_score, f1_score

def evaluate_recommendation_system(user_item_matrix, get_top_n_recommendations, top_n=10):
    true_positives = []
    false_positives = []
    false_negatives = []
    
    for user_id in user_item_matrix.index:
        # Actual interactions for the user
        actual_items = user_item_matrix.loc[user_id]
        actual_items = actual_items[actual_items > 0].index.tolist()  # Non-zero interactions as actual items
        
        # Predicted recommendations for the user
        recommended_items = get_top_n_recommendations(user_id, top_n)
        
        # Calculate True Positives, False Positives, and False Negatives
        for item in recommended_items:
            if item in actual_items:
                true_positives.append(1)
            else:
                false_positives.append(1)
        
        for item in actual_items:
            if item not in recommended_items:
                false_negatives.append(1)

    # Precision, Recall, F1 Score
    precision = sum(true_positives) / (sum(true_positives) + sum(false_positives)) if sum(true_positives) + sum(false_positives) > 0 else 0
    recall = sum(true_positives) / (sum(true_positives) + sum(false_negatives)) if sum(true_positives) + sum(false_negatives) > 0 else 0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0

    return precision, recall, f1

In [124]:
print(df.columns)

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [129]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Assuming you have your anime data in 'df'
# Example: Convert 'genre' column to a list of genres (split by commas)
df['genre_list'] = df['genre'].apply(lambda x: x.split(','))

# Convert 'genre_list' to a binary matrix (one-hot encoding)
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
genre_matrix = mlb.fit_transform(df['genre_list'])

# Add the genre binary matrix to the dataframe
genre_df = pd.DataFrame(genre_matrix, columns=mlb.classes_)

# Calculate similarity between anime based on genre and rating
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(genre_df)

# For a given anime (e.g., anime with id 1), find similar items
anime_index = df[df['anime_id'] == 1].index[0]
similar_anime = list(df.iloc[similarity_matrix[anime_index].argsort()[-5:]]['name'])

print(similar_anime)

['Waga Seishun no Arcadia: Mugen Kidou SSX', 'Uchuu Kaizoku Captain Harlock: Arcadia-gou no Nazo', 'Seihou Tenshi Angel Links', 'Cowboy Bebop: Yose Atsume Blues', 'Cowboy Bebop']

In [131]:
from sklearn.metrics import precision_score, recall_score
import numpy as np

# True relevant items (from user feedback or external data)
true_relevant_items = np.array([1, 3, 5, 7, 8])

# Recommended items
recommended_items = np.array([1, 2, 3, 4, 5])

# Precision at k (using 'micro' or 'macro' for multiclass)
precision_at_k = precision_score(true_relevant_items, recommended_items, average='micro')  # Or 'macro', 'weighted'

# Recall at k
recall_at_k = recall_score(true_relevant_items, recommended_items, average='micro')  # Or 'macro', 'weighted'

print(f"Precision@k: {precision_at_k}")
print(f"Recall@k: {recall_at_k}")

Precision@k: 0.2
Recall@k: 0.2